/**
 * Proactive Suggestion Types
 * Type definitions for the proactive suggestion scheduler system
 *
 * This file provides comprehensive type definitions for the UX-005 task:
 * Building a proactive suggestion scheduler that generates daily suggestions
 * based on user data for actionable items.
 */

/**
 * Core ProactiveSuggestion interface
 * Represents an actionable suggestion generated by the system
 */
export interface ProactiveSuggestion {
  /** Unique identifier for the suggestion */
  id: string;

  /** Type of suggestion (determines icon, styling, and behavior) */
  type: SuggestionTypeEnum;

  /** Priority level for display ordering and notification */
  priority: PriorityLevel;

  /** Short, actionable title (e.g., "3 bills due in 7 days") */
  title: string;

  /** Longer description with context and details */
  description: string;

  /** Optional action the user can take */
  action?: SuggestionAction;

  /** When this suggestion should expire (null = never) */
  expiresAt?: Date;

  /** Additional metadata for context */
  metadata?: Record<string, any>;
}

/**
 * Suggestion types that can be generated
 */
export enum SuggestionTypeEnum {
  /** Bills due in next 7 days */
  PAYMENT_DUE = 'PAYMENT_DUE',

  /** Invoices past their due date */
  OVERDUE_INVOICE = 'OVERDUE_INVOICE',

  /** Cash balance below threshold */
  LOW_CASH = 'LOW_CASH',

  /** Upcoming tax filing deadlines */
  TAX_DEADLINE = 'TAX_DEADLINE',

  /** Bank transactions needing reconciliation */
  UNRECONCILED = 'UNRECONCILED',

  /** Bank transactions without categories */
  UNCATEGORIZED = 'UNCATEGORIZED',

  /** General insights and tips */
  INSIGHT = 'INSIGHT',

  /** Optimization opportunities */
  OPTIMIZATION = 'OPTIMIZATION',

  /** Anomalies detected in data */
  ANOMALY = 'ANOMALY',

  /** Quick actions available */
  QUICK_ACTION = 'QUICK_ACTION',
}

/**
 * Priority levels for suggestions
 */
export type PriorityLevel = 'HIGH' | 'MEDIUM' | 'LOW';

/**
 * Action that can be performed from a suggestion
 */
export interface SuggestionAction {
  /** Type of action (navigate, execute, chat, etc.) */
  type: ActionType;

  /** URL or route to navigate to */
  target: string;

  /** Display label for the action button */
  label?: string;

  /** Additional parameters for the action */
  params?: Record<string, any>;

  /** Whether to show a confirmation dialog */
  requiresConfirmation?: boolean;
}

/**
 * Types of actions that can be triggered
 */
export type ActionType =
  | 'navigate'      // Navigate to a page
  | 'execute'       // Execute a backend action
  | 'chat'          // Open chat with pre-filled message
  | 'external'      // Open external URL
  | 'dismiss';      // Just dismiss the suggestion

/**
 * Context for suggestion generation
 * Passed to generators to provide org/user context
 */
export interface SuggestionGenerationContext {
  /** Organization ID */
  orgId: string;

  /** Optional user ID (null for org-wide suggestions) */
  userId?: string;

  /** Current date for time-based calculations */
  currentDate: Date;

  /** Optional date range for analysis */
  dateRange?: {
    start: Date;
    end: Date;
  };
}

/**
 * Result from a suggestion generator
 */
export interface GeneratorOutput {
  /** Generated suggestions */
  suggestions: ProactiveSuggestion[];

  /** Number of items analyzed */
  itemsAnalyzed?: number;

  /** Any errors encountered (for logging) */
  errors?: string[];
}

/**
 * Suggestion generator interface
 * All generators must implement this interface
 */
export interface ISuggestionGenerator {
  /** Generator name for logging */
  name: string;

  /** Generate suggestions for the given context */
  generate(context: SuggestionGenerationContext): Promise<GeneratorOutput>;
}

/**
 * Scheduler configuration
 */
export interface SchedulerConfig {
  /** Cron expression for when to run */
  schedule: string;

  /** Timezone for scheduling */
  timezone: string;

  /** Batch size for processing orgs */
  batchSize: number;

  /** Whether scheduler is enabled */
  enabled: boolean;
}

/**
 * Scheduler run result
 */
export interface SchedulerRunResult {
  /** Number of organizations processed */
  organizationsProcessed: number;

  /** Total suggestions created */
  suggestionsCreated: number;

  /** Total notifications sent */
  notificationsSent: number;

  /** Duration in milliseconds */
  durationMs: number;

  /** Any errors encountered */
  errors: Array<{
    orgId: string;
    error: string;
  }>;
}

/**
 * Bill payment suggestion (specialized)
 */
export interface BillPaymentSuggestion extends ProactiveSuggestion {
  type: SuggestionTypeEnum.PAYMENT_DUE;
  metadata: {
    billIds: string[];
    totalAmount: number;
    currency: string;
    dueDate: Date;
    vendorNames: string[];
  };
}

/**
 * Overdue invoice suggestion (specialized)
 */
export interface OverdueInvoiceSuggestion extends ProactiveSuggestion {
  type: SuggestionTypeEnum.OVERDUE_INVOICE;
  metadata: {
    invoiceIds: string[];
    totalAmount: number;
    currency: string;
    customerNames: string[];
    oldestDueDate: Date;
    daysOverdue: number;
  };
}

/**
 * Cash flow alert suggestion (specialized)
 */
export interface CashFlowSuggestion extends ProactiveSuggestion {
  type: SuggestionTypeEnum.LOW_CASH;
  metadata: {
    currentBalance: number;
    threshold: number;
    projectedBalance?: number;
    daysUntilLow?: number;
    runwayMonths?: number;
  };
}

/**
 * Tax deadline suggestion (specialized)
 */
export interface TaxDeadlineSuggestion extends ProactiveSuggestion {
  type: SuggestionTypeEnum.TAX_DEADLINE;
  metadata: {
    deadlineType: string;
    dueDate: Date;
    daysRemaining: number;
    estimatedAmount?: number;
    filingType: 'monthly' | 'quarterly' | 'yearly';
  };
}

/**
 * Bank reconciliation suggestion (specialized)
 */
export interface BankReconciliationSuggestion extends ProactiveSuggestion {
  type: SuggestionTypeEnum.UNRECONCILED;
  metadata: {
    transactionCount: number;
    totalAmount: number;
    oldestTransactionDate?: Date;
    accountIds: string[];
  };
}

/**
 * Notification payload for high-priority suggestions
 */
export interface SuggestionNotification {
  /** Suggestion that triggered the notification */
  suggestionId: string;

  /** User to notify */
  userId: string;

  /** Organization context */
  orgId: string;

  /** Notification title */
  title: string;

  /** Notification body */
  message: string;

  /** Priority (for notification channels) */
  priority: 1 | 2 | 3 | 4 | 5;

  /** Deep link URL */
  actionUrl?: string;

  /** Notification data */
  data?: Record<string, any>;
}

/**
 * Database model for persisted suggestions
 */
export interface PersistedSuggestion {
  id: string;
  orgId: string;
  userId: string | null;
  type: string;
  priority: string;
  title: string;
  description: string;
  actionLabel: string | null;
  actionType: string | null;
  actionParams: Record<string, any> | null;
  entityType: string | null;
  entityId: string | null;
  data: Record<string, any> | null;
  status: 'PENDING' | 'VIEWED' | 'ACTED' | 'DISMISSED' | 'EXPIRED';
  viewedAt: Date | null;
  actedAt: Date | null;
  dismissedAt: Date | null;
  showAfter: Date;
  expiresAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
}
