/**
 * Generate Report Action Handler
 * Handles report generation requests via chatbot
 */

import { Injectable } from '@nestjs/common';
import { BaseActionHandler } from './base.handler';
import {
  ActionType,
  ActionResult,
  ActionContext,
  ParameterDefinition,
} from '../action.types';
import { ReportsService } from '../../../reports/reports.service';

@Injectable()
export class GenerateReportHandler extends BaseActionHandler {
  constructor(private reportsService: ReportsService) {
    super('GenerateReportHandler');
  }

  get actionType(): ActionType {
    return ActionType.GENERATE_REPORT;
  }

  getRequiredParameters(): ParameterDefinition[] {
    return [
      {
        name: 'reportType',
        type: 'string',
        required: true,
        description: 'Type of report to generate',
        validation: (value) =>
          ['income', 'expense', 'tax', 'profit-loss', 'balance-sheet'].includes(
            value.toLowerCase(),
          ),
      },
      {
        name: 'fromDate',
        type: 'string',
        required: true,
        description: 'Start date for report (ISO format)',
      },
      {
        name: 'toDate',
        type: 'string',
        required: true,
        description: 'End date for report (ISO format)',
      },
      {
        name: 'format',
        type: 'string',
        required: false,
        description: 'Report format (pdf, excel, csv)',
        default: 'pdf',
        validation: (value) => ['pdf', 'excel', 'csv'].includes(value.toLowerCase()),
      },
    ];
  }

  async execute(
    params: Record<string, any>,
    context: ActionContext,
  ): Promise<ActionResult> {
    try {
      // Check permission
      if (!this.hasPermission(context, 'reports:generate')) {
        return this.error(
          'You do not have permission to generate reports',
          'PERMISSION_DENIED',
        );
      }

      // Normalize parameters
      const normalized = this.normalizeParams(params);

      // Validate date range
      const fromDate = new Date(normalized.fromDate);
      const toDate = new Date(normalized.toDate);

      if (fromDate > toDate) {
        return this.error('Start date must be before end date', 'VALIDATION_ERROR');
      }

      // Generate report based on type
      let reportResult;
      const reportType = normalized.reportType.toLowerCase();

      switch (reportType) {
        case 'income':
        case 'expense':
          reportResult = await this.reportsService.getFinancialReport(
            context.organizationId,
            {
              fromDate: normalized.fromDate,
              toDate: normalized.toDate,
            },
          );
          break;

        case 'profit-loss':
        case 'balance-sheet':
          reportResult = await this.reportsService.getFinancialReport(
            context.organizationId,
            {
              fromDate: normalized.fromDate,
              toDate: normalized.toDate,
            },
          );
          break;

        case 'tax':
          reportResult = await this.reportsService.getTaxReport(
            context.organizationId,
            {
              fromDate: normalized.fromDate,
              toDate: normalized.toDate,
            },
          );
          break;

        default:
          return this.error(`Unsupported report type: ${reportType}`, 'VALIDATION_ERROR');
      }

      this.logger.log(
        `Report ${reportType} generated by AI assistant for user ${context.userId}`,
      );

      return this.success(
        `${this.capitalizeFirst(reportType)} report generated successfully for ${this.formatDateRange(fromDate, toDate)}`,
        undefined,
        'Report',
        {
          reportType: reportType,
          format: normalized.format || 'pdf',
          fromDate: normalized.fromDate,
          toDate: normalized.toDate,
          reportData: reportResult,
        },
      );
    } catch (error) {
      this.logger.error('Failed to generate report:', error);
      return this.error(
        'Failed to generate report',
        error.message || 'Unknown error',
      );
    }
  }

  /**
   * Capitalize first letter of string
   */
  private capitalizeFirst(str: string): string {
    return str.charAt(0).toUpperCase() + str.slice(1);
  }

  /**
   * Format date range for display
   */
  private formatDateRange(from: Date, to: Date): string {
    const options: Intl.DateTimeFormatOptions = {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
    };
    return `${from.toLocaleDateString('en-US', options)} - ${to.toLocaleDateString('en-US', options)}`;
  }
}
