import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  PayrollReportType,
  ReportFormat,
  ReportMetadata,
} from '../types/payroll-report.types';

/**
 * Base Report Response DTO
 */
export class ReportResponseDto {
  @ApiProperty({
    description: 'Unique report ID',
    example: 'report-123e4567-e89b-12d3-a456-426614174000',
  })
  reportId: string;

  @ApiProperty({
    description: 'Report type',
    enum: PayrollReportType,
    example: PayrollReportType.PAYROLL_SUMMARY,
  })
  reportType: PayrollReportType;

  @ApiProperty({
    description: 'Report format',
    enum: ReportFormat,
    example: ReportFormat.PDF,
  })
  format: ReportFormat;

  @ApiProperty({
    description: 'Report generation timestamp',
    example: '2024-12-02T10:30:00Z',
  })
  generatedAt: Date;

  @ApiProperty({
    description: 'Report generated by user ID',
    example: 'user-123',
  })
  generatedBy: string;

  @ApiProperty({
    description: 'Company UUID',
    example: '7b5b3f0e-4c8d-4f7e-8c3d-1234567890ab',
  })
  companyUuid: string;

  @ApiProperty({
    description: 'Date range for the report',
    example: { start: '2024-01-01', end: '2024-12-31' },
  })
  dateRange: {
    start: string;
    end: string;
  };

  @ApiPropertyOptional({
    description: 'Download URL for the report (if format is PDF/Excel)',
    example: 'https://storage.example.com/reports/report-123.pdf',
  })
  downloadUrl?: string;

  @ApiPropertyOptional({
    description: 'Report data (if format is JSON)',
    example: {},
  })
  data?: any;

  @ApiPropertyOptional({
    description: 'Report file size in bytes',
    example: 1024567,
  })
  fileSizeBytes?: number;

  @ApiPropertyOptional({
    description: 'Cache expiration time',
    example: '2024-12-02T22:30:00Z',
  })
  expiresAt?: Date;
}

/**
 * Payroll Summary Response
 */
export class PayrollSummaryResponseDto extends ReportResponseDto {
  @ApiProperty({
    description: 'Summary statistics',
    example: {
      totalPayrolls: 12,
      totalGrossPay: 500000,
      totalNetPay: 375000,
      totalTaxes: 100000,
      totalDeductions: 25000,
    },
  })
  summary: {
    totalPayrolls: number;
    totalGrossPay: number;
    totalNetPay: number;
    totalTaxes: number;
    totalDeductions: number;
  };
}

/**
 * Employee Earnings Response
 */
export class EmployeeEarningsResponseDto extends ReportResponseDto {
  @ApiProperty({
    description: 'Summary statistics',
    example: {
      totalEmployees: 50,
      totalGrossPay: 500000,
      totalNetPay: 375000,
      averageGrossPay: 10000,
    },
  })
  summary: {
    totalEmployees: number;
    totalGrossPay: number;
    totalNetPay: number;
    averageGrossPay: number;
  };
}

/**
 * Tax Liability Response
 */
export class TaxLiabilityResponseDto extends ReportResponseDto {
  @ApiProperty({
    description: 'Tax liability summary',
    example: {
      totalFederalTax: 75000,
      totalStateTax: 15000,
      totalLocalTax: 5000,
      totalTaxLiability: 95000,
    },
  })
  summary: {
    totalFederalTax: number;
    totalStateTax: number;
    totalLocalTax: number;
    totalTaxLiability: number;
  };
}

/**
 * 401(k) Contribution Response
 */
export class FourOhOneKResponseDto extends ReportResponseDto {
  @ApiProperty({
    description: '401(k) contribution summary',
    example: {
      totalParticipants: 45,
      totalEmployeeContributions: 125000,
      totalEmployerMatch: 62500,
      totalContributions: 187500,
      averageContributionRate: 6.5,
    },
  })
  summary: {
    totalParticipants: number;
    totalEmployeeContributions: number;
    totalEmployerMatch: number;
    totalContributions: number;
    averageContributionRate: number;
  };
}

/**
 * Benefits Deduction Response
 */
export class BenefitsDeductionResponseDto extends ReportResponseDto {
  @ApiProperty({
    description: 'Benefits deduction summary',
    example: {
      totalEmployees: 50,
      totalHealthInsurance: 30000,
      totalRetirement: 125000,
      totalOther: 10000,
      totalDeductions: 165000,
    },
  })
  summary: {
    totalEmployees: number;
    totalHealthInsurance: number;
    totalRetirement: number;
    totalOther: number;
    totalDeductions: number;
  };
}

/**
 * YTD Report Response
 */
export class YTDReportResponseDto extends ReportResponseDto {
  @ApiProperty({
    description: 'YTD summary',
    example: {
      totalEmployees: 50,
      totalGrossPay: 5000000,
      totalTaxes: 1000000,
      totalDeductions: 250000,
      totalNetPay: 3750000,
    },
  })
  summary: {
    totalEmployees: number;
    totalGrossPay: number;
    totalTaxes: number;
    totalDeductions: number;
    totalNetPay: number;
  };
}

/**
 * Quarterly Tax Report Response
 */
export class QuarterlyTaxResponseDto extends ReportResponseDto {
  @ApiProperty({
    description: 'Quarterly tax summary',
    example: {
      quarter: 1,
      year: 2024,
      totalWages: 1250000,
      totalFederalIncomeTax: 187500,
      totalSocialSecurity: 155000,
      totalMedicare: 36250,
      totalTaxLiability: 378750,
    },
  })
  summary: {
    quarter: number;
    year: number;
    totalWages: number;
    totalFederalIncomeTax: number;
    totalSocialSecurity: number;
    totalMedicare: number;
    totalTaxLiability: number;
  };
}

/**
 * Annual W-2 Summary Response
 */
export class AnnualW2SummaryResponseDto extends ReportResponseDto {
  @ApiProperty({
    description: 'W-2 summary',
    example: {
      year: 2024,
      totalEmployees: 50,
      totalWages: 5000000,
      totalFederalIncomeTax: 750000,
      totalSocialSecurityTax: 310000,
      totalMedicareTax: 72500,
    },
  })
  summary: {
    year: number;
    totalEmployees: number;
    totalWages: number;
    totalFederalIncomeTax: number;
    totalSocialSecurityTax: number;
    totalMedicareTax: number;
  };
}

/**
 * Report Schedule Response
 */
export class ReportScheduleResponseDto {
  @ApiProperty({
    description: 'Schedule ID',
    example: 'schedule-123',
  })
  id: string;

  @ApiProperty({
    description: 'Report type',
    enum: PayrollReportType,
    example: PayrollReportType.PAYROLL_SUMMARY,
  })
  reportType: PayrollReportType;

  @ApiProperty({
    description: 'Company UUID',
    example: '7b5b3f0e-4c8d-4f7e-8c3d-1234567890ab',
  })
  companyUuid: string;

  @ApiProperty({
    description: 'Schedule frequency',
    example: 'monthly',
  })
  frequency: string;

  @ApiProperty({
    description: 'Recipients',
    type: [String],
    example: ['user@example.com'],
  })
  recipients: string[];

  @ApiProperty({
    description: 'Report format',
    enum: ReportFormat,
    example: ReportFormat.PDF,
  })
  format: ReportFormat;

  @ApiProperty({
    description: 'Schedule enabled',
    example: true,
  })
  enabled: boolean;

  @ApiProperty({
    description: 'Next run date',
    example: '2024-12-15T09:00:00Z',
  })
  nextRunDate: Date;

  @ApiPropertyOptional({
    description: 'Last run date',
    example: '2024-11-15T09:00:00Z',
  })
  lastRunDate?: Date;

  @ApiProperty({
    description: 'Created at',
    example: '2024-01-01T00:00:00Z',
  })
  createdAt: Date;

  @ApiProperty({
    description: 'Updated at',
    example: '2024-12-01T00:00:00Z',
  })
  updatedAt: Date;
}

/**
 * Report List Response
 */
export class ReportListResponseDto {
  @ApiProperty({
    description: 'List of reports',
    type: [ReportResponseDto],
  })
  reports: ReportResponseDto[];

  @ApiProperty({
    description: 'Total count',
    example: 100,
  })
  total: number;

  @ApiProperty({
    description: 'Page number',
    example: 1,
  })
  page: number;

  @ApiProperty({
    description: 'Page size',
    example: 20,
  })
  pageSize: number;

  @ApiProperty({
    description: 'Total pages',
    example: 5,
  })
  totalPages: number;
}

/**
 * Error Response
 */
export class ReportErrorResponseDto {
  @ApiProperty({
    description: 'Error code',
    example: 'REPORT_GENERATION_FAILED',
  })
  code: string;

  @ApiProperty({
    description: 'Error message',
    example: 'Failed to generate report due to missing data',
  })
  message: string;

  @ApiProperty({
    description: 'Error details',
    example: { missingData: 'payroll records' },
  })
  details?: any;

  @ApiProperty({
    description: 'Timestamp',
    example: '2024-12-02T10:30:00Z',
  })
  timestamp: Date;
}
