import {
  TinkAccount,
  TinkAccountType,
  TinkTransaction,
  TinkTransactionStatus,
  TinkTransactionType,
  TinkProvider,
  TinkToken,
} from '../tink.types';

/**
 * Mock Data Utility for Tink Development/Testing
 * Provides realistic test data for development without real bank connections
 */
export class TinkMockDataUtil {
  /**
   * Generate mock OAuth2 token
   */
  static generateMockToken(): TinkToken {
    return {
      accessToken: 'mock_access_token_' + Math.random().toString(36).substring(7),
      refreshToken: 'mock_refresh_token_' + Math.random().toString(36).substring(7),
      tokenType: 'Bearer',
      expiresIn: 3600,
      scope: 'accounts:read,balances:read,transactions:read',
      expiresAt: new Date(Date.now() + 3600 * 1000),
    };
  }

  /**
   * Generate mock bank accounts
   */
  static generateMockAccounts(): TinkAccount[] {
    return [
      {
        id: 'mock_account_checking_1',
        identifiers: {
          iban: 'DE89370400440532013000',
          accountNumber: '532013000',
        },
        name: 'Main Checking Account',
        type: TinkAccountType.CHECKING,
        balances: {
          booked: {
            amount: {
              value: 15234.56,
              currencyCode: 'EUR',
            },
          },
          available: {
            amount: {
              value: 15234.56,
              currencyCode: 'EUR',
            },
          },
        },
        dates: {
          lastRefreshed: new Date(),
        },
      },
      {
        id: 'mock_account_savings_1',
        identifiers: {
          iban: 'DE89370400440532013001',
          accountNumber: '532013001',
        },
        name: 'Savings Account',
        type: TinkAccountType.SAVINGS,
        balances: {
          booked: {
            amount: {
              value: 45678.90,
              currencyCode: 'EUR',
            },
          },
          available: {
            amount: {
              value: 45678.90,
              currencyCode: 'EUR',
            },
          },
        },
        dates: {
          lastRefreshed: new Date(),
        },
      },
      {
        id: 'mock_account_credit_1',
        identifiers: {
          accountNumber: '5321-****-****-1234',
        },
        name: 'Business Credit Card',
        type: TinkAccountType.CREDIT_CARD,
        balances: {
          booked: {
            amount: {
              value: -2345.67,
              currencyCode: 'EUR',
            },
          },
          available: {
            amount: {
              value: 7654.33,
              currencyCode: 'EUR',
            },
          },
        },
        dates: {
          lastRefreshed: new Date(),
        },
      },
    ];
  }

  /**
   * Generate mock transactions for an account
   */
  static generateMockTransactions(accountId: string, count: number = 50): TinkTransaction[] {
    const transactions: TinkTransaction[] = [];
    const now = new Date();

    const merchantNames = [
      'Amazon',
      'Office Depot',
      'Starbucks',
      'Shell Gas Station',
      'LinkedIn',
      'Adobe',
      'AWS Services',
      'Microsoft',
      'Google Ads',
      'Salary Payment',
      'Client Payment - ABC Corp',
      'Rent Payment',
      'Electricity Bill',
      'Insurance Premium',
      'Bank Fee',
    ];

    const transactionTypes = [
      TinkTransactionType.PAYMENT,
      TinkTransactionType.TRANSFER,
      TinkTransactionType.WITHDRAWAL,
      TinkTransactionType.DEPOSIT,
      TinkTransactionType.FEE,
    ];

    for (let i = 0; i < count; i++) {
      const daysAgo = Math.floor(Math.random() * 90);
      const date = new Date(now.getTime() - daysAgo * 24 * 60 * 60 * 1000);
      const isDeposit = Math.random() > 0.6;
      const amount = isDeposit
        ? Math.random() * 5000 + 100
        : -(Math.random() * 500 + 10);

      const merchantName = merchantNames[Math.floor(Math.random() * merchantNames.length)];
      const txnType = transactionTypes[Math.floor(Math.random() * transactionTypes.length)];

      transactions.push({
        id: `mock_txn_${accountId}_${i}`,
        accountId,
        amount: {
          value: parseFloat(amount.toFixed(2)),
          currencyCode: 'EUR',
        },
        dates: {
          booked: date,
          value: date,
        },
        descriptions: {
          original: merchantName,
          display: merchantName,
        },
        identifiers: {
          providerTransactionId: `MOCK-${Date.now()}-${i}`,
        },
        merchantInformation: {
          merchantName: merchantName,
          merchantCategoryCode: '5411',
        },
        status: Math.random() > 0.9 ? TinkTransactionStatus.PENDING : TinkTransactionStatus.BOOKED,
        types: {
          type: txnType,
          financialInstitutionType: 'SEPA',
        },
        providerMutability: 'MUTABILITY_IMMUTABLE',
      });
    }

    // Sort by date descending
    return transactions.sort((a, b) => b.dates.booked.getTime() - a.dates.booked.getTime());
  }

  /**
   * Generate mock providers (banks)
   * @param market - Market code (e.g. 'DE', 'AT', 'FR') - filters providers by market if provided
   */
  static generateMockProviders(market?: string): TinkProvider[] {
    const defaultFields = [
      { name: 'username', description: 'Username', optional: false, numeric: false, immutable: false, sensitive: false },
      { name: 'password', description: 'Password', optional: false, numeric: false, immutable: false, sensitive: true },
    ];
    const defaultCapabilities = ['ACCOUNTS', 'TRANSACTIONS', 'BALANCE'];

    const allProviders: TinkProvider[] = [
      // German Banks
      {
        name: 'de-deutsche-bank',
        displayName: 'Deutsche Bank',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'German Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'DE',
        financialInstitution: { id: 'de-deutsche-bank', name: 'Deutsche Bank' },
      },
      {
        name: 'de-commerzbank',
        displayName: 'Commerzbank',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'German Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'DE',
        financialInstitution: { id: 'de-commerzbank', name: 'Commerzbank' },
      },
      {
        name: 'de-sparkasse',
        displayName: 'Sparkasse',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'German Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'DE',
        financialInstitution: { id: 'de-sparkasse', name: 'Sparkasse' },
      },
      {
        name: 'de-volksbank',
        displayName: 'Volksbank Raiffeisenbank',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'German Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'DE',
        financialInstitution: { id: 'de-volksbank', name: 'Volksbank Raiffeisenbank' },
      },
      {
        name: 'de-ing',
        displayName: 'ING Deutschland',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'German Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'DE',
        financialInstitution: { id: 'de-ing', name: 'ING Deutschland' },
      },
      {
        name: 'de-n26',
        displayName: 'N26',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'German Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'DE',
        financialInstitution: { id: 'de-n26', name: 'N26' },
      },
      {
        name: 'de-dkb',
        displayName: 'DKB Deutsche Kreditbank',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'German Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'DE',
        financialInstitution: { id: 'de-dkb', name: 'DKB Deutsche Kreditbank' },
      },
      {
        name: 'de-postbank',
        displayName: 'Postbank',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'German Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'DE',
        financialInstitution: { id: 'de-postbank', name: 'Postbank' },
      },
      {
        name: 'de-hypovereinsbank',
        displayName: 'HypoVereinsbank',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'German Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'DE',
        financialInstitution: { id: 'de-hypovereinsbank', name: 'HypoVereinsbank' },
      },
      {
        name: 'de-comdirect',
        displayName: 'comdirect',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'German Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'DE',
        financialInstitution: { id: 'de-comdirect', name: 'comdirect' },
      },
      {
        name: 'de-targobank',
        displayName: 'Targobank',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'German Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'DE',
        financialInstitution: { id: 'de-targobank', name: 'Targobank' },
      },
      {
        name: 'de-santander',
        displayName: 'Santander Deutschland',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'German Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'DE',
        financialInstitution: { id: 'de-santander', name: 'Santander Deutschland' },
      },
      {
        name: 'de-consorsbank',
        displayName: 'Consorsbank',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'German Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'DE',
        financialInstitution: { id: 'de-consorsbank', name: 'Consorsbank' },
      },
      {
        name: 'de-sparda-bank',
        displayName: 'Sparda-Bank',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'German Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'DE',
        financialInstitution: { id: 'de-sparda-bank', name: 'Sparda-Bank' },
      },
      {
        name: 'de-psd-bank',
        displayName: 'PSD Bank',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'German Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'DE',
        financialInstitution: { id: 'de-psd-bank', name: 'PSD Bank' },
      },
      {
        name: 'de-gls-bank',
        displayName: 'GLS Bank',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'German Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'DE',
        financialInstitution: { id: 'de-gls-bank', name: 'GLS Bank' },
      },
      {
        name: 'de-triodos-bank',
        displayName: 'Triodos Bank Deutschland',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'German Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'DE',
        financialInstitution: { id: 'de-triodos-bank', name: 'Triodos Bank Deutschland' },
      },
      {
        name: 'de-olb',
        displayName: 'Oldenburgische Landesbank',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'German Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'DE',
        financialInstitution: { id: 'de-olb', name: 'Oldenburgische Landesbank' },
      },
      {
        name: 'de-bbbank',
        displayName: 'BBBank',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'German Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'DE',
        financialInstitution: { id: 'de-bbbank', name: 'BBBank' },
      },
      {
        name: 'de-norisbank',
        displayName: 'Norisbank',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'German Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'DE',
        financialInstitution: { id: 'de-norisbank', name: 'Norisbank' },
      },
      {
        name: 'de-fidor-bank',
        displayName: 'Fidor Bank',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'German Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'DE',
        financialInstitution: { id: 'de-fidor-bank', name: 'Fidor Bank' },
      },
      {
        name: 'de-wuestenrot',
        displayName: 'Wüstenrot Bank',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'German Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'DE',
        financialInstitution: { id: 'de-wuestenrot', name: 'Wüstenrot Bank' },
      },
      {
        name: 'de-1822direkt',
        displayName: '1822direkt',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'German Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'DE',
        financialInstitution: { id: 'de-1822direkt', name: '1822direkt' },
      },
      {
        name: 'de-netbank',
        displayName: 'netbank',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'German Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'DE',
        financialInstitution: { id: 'de-netbank', name: 'netbank' },
      },
      {
        name: 'de-tomorrow-bank',
        displayName: 'Tomorrow Bank',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'German Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'DE',
        financialInstitution: { id: 'de-tomorrow-bank', name: 'Tomorrow Bank' },
      },
      {
        name: 'de-vivid-money',
        displayName: 'Vivid Money',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'German Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'DE',
        financialInstitution: { id: 'de-vivid-money', name: 'Vivid Money' },
      },
      {
        name: 'de-bunq',
        displayName: 'bunq',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'German Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'DE',
        financialInstitution: { id: 'de-bunq', name: 'bunq' },
      },
      {
        name: 'de-revolut',
        displayName: 'Revolut Deutschland',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'German Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'DE',
        financialInstitution: { id: 'de-revolut', name: 'Revolut Deutschland' },
      },
      // Austrian Banks
      {
        name: 'at-erste-bank',
        displayName: 'Erste Bank Austria',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'Austrian Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'AT',
        financialInstitution: { id: 'at-erste-bank', name: 'Erste Bank Austria' },
      },
      {
        name: 'at-raiffeisen',
        displayName: 'Raiffeisen Bank Austria',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'Austrian Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'AT',
        financialInstitution: { id: 'at-raiffeisen', name: 'Raiffeisen Bank Austria' },
      },
      {
        name: 'at-bank-austria',
        displayName: 'Bank Austria',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'Austrian Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'AT',
        financialInstitution: { id: 'at-bank-austria', name: 'Bank Austria' },
      },
      {
        name: 'at-sparkasse',
        displayName: 'Sparkasse Austria',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Austrian Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'AT',
        financialInstitution: { id: 'at-sparkasse', name: 'Sparkasse Austria' },
      },
      {
        name: 'at-bawag-psk',
        displayName: 'BAWAG PSK',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'Austrian Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'AT',
        financialInstitution: { id: 'at-bawag-psk', name: 'BAWAG PSK' },
      },
      {
        name: 'at-oberbank',
        displayName: 'Oberbank',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Austrian Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'AT',
        financialInstitution: { id: 'at-oberbank', name: 'Oberbank' },
      },
      {
        name: 'at-bks-bank',
        displayName: 'BKS Bank',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Austrian Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'AT',
        financialInstitution: { id: 'at-bks-bank', name: 'BKS Bank' },
      },
      {
        name: 'at-hypo-tirol',
        displayName: 'Hypo Tirol Bank',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Austrian Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'AT',
        financialInstitution: { id: 'at-hypo-tirol', name: 'Hypo Tirol Bank' },
      },
      {
        name: 'at-hypo-vorarlberg',
        displayName: 'Hypo Vorarlberg',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Austrian Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'AT',
        financialInstitution: { id: 'at-hypo-vorarlberg', name: 'Hypo Vorarlberg' },
      },
      {
        name: 'at-addiko-bank',
        displayName: 'Addiko Bank',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Austrian Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'AT',
        financialInstitution: { id: 'at-addiko-bank', name: 'Addiko Bank' },
      },
      {
        name: 'at-easybank',
        displayName: 'easybank',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'Austrian Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'AT',
        financialInstitution: { id: 'at-easybank', name: 'easybank' },
      },
      {
        name: 'at-denizbank',
        displayName: 'Denizbank Austria',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Austrian Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'AT',
        financialInstitution: { id: 'at-denizbank', name: 'Denizbank Austria' },
      },
      {
        name: 'at-hello-bank',
        displayName: 'Hello Bank Austria',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Austrian Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'AT',
        financialInstitution: { id: 'at-hello-bank', name: 'Hello Bank Austria' },
      },
      {
        name: 'at-direktanlage',
        displayName: 'Direktanlage.at',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Austrian Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'AT',
        financialInstitution: { id: 'at-direktanlage', name: 'Direktanlage.at' },
      },
      // French Banks
      {
        name: 'fr-bnp-paribas',
        displayName: 'BNP Paribas',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'French Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'FR',
        financialInstitution: { id: 'fr-bnp-paribas', name: 'BNP Paribas' },
      },
      {
        name: 'fr-societe-generale',
        displayName: 'Société Générale',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'French Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'FR',
        financialInstitution: { id: 'fr-societe-generale', name: 'Société Générale' },
      },
      {
        name: 'fr-credit-agricole',
        displayName: 'Crédit Agricole',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'French Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'FR',
        financialInstitution: { id: 'fr-credit-agricole', name: 'Crédit Agricole' },
      },
      {
        name: 'fr-credit-mutuel',
        displayName: 'Crédit Mutuel',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'French Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'FR',
        financialInstitution: { id: 'fr-credit-mutuel', name: 'Crédit Mutuel' },
      },
      {
        name: 'fr-la-banque-postale',
        displayName: 'La Banque Postale',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'French Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'FR',
        financialInstitution: { id: 'fr-la-banque-postale', name: 'La Banque Postale' },
      },
      {
        name: 'fr-cic',
        displayName: 'CIC',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'French Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'FR',
        financialInstitution: { id: 'fr-cic', name: 'CIC' },
      },
      {
        name: 'fr-lcl',
        displayName: 'LCL',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'French Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'FR',
        financialInstitution: { id: 'fr-lcl', name: 'LCL' },
      },
      {
        name: 'fr-boursorama',
        displayName: 'Boursorama',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'French Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'FR',
        financialInstitution: { id: 'fr-boursorama', name: 'Boursorama' },
      },
      {
        name: 'fr-fortuneo',
        displayName: 'Fortuneo',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'French Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'FR',
        financialInstitution: { id: 'fr-fortuneo', name: 'Fortuneo' },
      },
      {
        name: 'fr-hello-bank',
        displayName: 'Hello bank! France',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'French Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'FR',
        financialInstitution: { id: 'fr-hello-bank', name: 'Hello bank! France' },
      },
      // Italian Banks
      {
        name: 'it-intesa-sanpaolo',
        displayName: 'Intesa Sanpaolo',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'Italian Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'IT',
        financialInstitution: { id: 'it-intesa-sanpaolo', name: 'Intesa Sanpaolo' },
      },
      {
        name: 'it-unicredit',
        displayName: 'UniCredit',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'Italian Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'IT',
        financialInstitution: { id: 'it-unicredit', name: 'UniCredit' },
      },
      {
        name: 'it-banco-bpm',
        displayName: 'Banco BPM',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Italian Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'IT',
        financialInstitution: { id: 'it-banco-bpm', name: 'Banco BPM' },
      },
      {
        name: 'it-bper-banca',
        displayName: 'BPER Banca',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Italian Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'IT',
        financialInstitution: { id: 'it-bper-banca', name: 'BPER Banca' },
      },
      {
        name: 'it-monte-paschi-siena',
        displayName: 'Monte dei Paschi di Siena',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Italian Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'IT',
        financialInstitution: { id: 'it-monte-paschi-siena', name: 'Monte dei Paschi di Siena' },
      },
      {
        name: 'it-fineco-bank',
        displayName: 'Fineco Bank',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'Italian Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'IT',
        financialInstitution: { id: 'it-fineco-bank', name: 'Fineco Bank' },
      },
      {
        name: 'it-poste-italiane',
        displayName: 'Poste Italiane',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Italian Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'IT',
        financialInstitution: { id: 'it-poste-italiane', name: 'Poste Italiane' },
      },
      {
        name: 'it-ing-italia',
        displayName: 'ING Italia',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Italian Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'IT',
        financialInstitution: { id: 'it-ing-italia', name: 'ING Italia' },
      },
      {
        name: 'it-n26',
        displayName: 'N26 Italia',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Italian Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'IT',
        financialInstitution: { id: 'it-n26', name: 'N26 Italia' },
      },
      // Spanish Banks
      {
        name: 'es-santander',
        displayName: 'Santander España',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'Spanish Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'ES',
        financialInstitution: { id: 'es-santander', name: 'Santander España' },
      },
      {
        name: 'es-bbva',
        displayName: 'BBVA',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'Spanish Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'ES',
        financialInstitution: { id: 'es-bbva', name: 'BBVA' },
      },
      {
        name: 'es-caixabank',
        displayName: 'CaixaBank',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'Spanish Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'ES',
        financialInstitution: { id: 'es-caixabank', name: 'CaixaBank' },
      },
      {
        name: 'es-sabadell',
        displayName: 'Sabadell',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Spanish Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'ES',
        financialInstitution: { id: 'es-sabadell', name: 'Sabadell' },
      },
      {
        name: 'es-bankinter',
        displayName: 'Bankinter',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Spanish Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'ES',
        financialInstitution: { id: 'es-bankinter', name: 'Bankinter' },
      },
      {
        name: 'es-ing',
        displayName: 'ING España',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Spanish Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'ES',
        financialInstitution: { id: 'es-ing', name: 'ING España' },
      },
      {
        name: 'es-openbank',
        displayName: 'Openbank',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'Spanish Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'ES',
        financialInstitution: { id: 'es-openbank', name: 'Openbank' },
      },
      {
        name: 'es-evo-banco',
        displayName: 'EVO Banco',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Spanish Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'ES',
        financialInstitution: { id: 'es-evo-banco', name: 'EVO Banco' },
      },
      {
        name: 'es-n26',
        displayName: 'N26 España',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Spanish Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'ES',
        financialInstitution: { id: 'es-n26', name: 'N26 España' },
      },
      // Dutch Banks
      {
        name: 'nl-ing',
        displayName: 'ING',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'Dutch Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'NL',
        financialInstitution: { id: 'nl-ing', name: 'ING' },
      },
      {
        name: 'nl-rabobank',
        displayName: 'Rabobank',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'Dutch Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'NL',
        financialInstitution: { id: 'nl-rabobank', name: 'Rabobank' },
      },
      {
        name: 'nl-abn-amro',
        displayName: 'ABN AMRO',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'Dutch Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'NL',
        financialInstitution: { id: 'nl-abn-amro', name: 'ABN AMRO' },
      },
      {
        name: 'nl-sns-bank',
        displayName: 'SNS Bank',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Dutch Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'NL',
        financialInstitution: { id: 'nl-sns-bank', name: 'SNS Bank' },
      },
      {
        name: 'nl-asn-bank',
        displayName: 'ASN Bank',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Dutch Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'NL',
        financialInstitution: { id: 'nl-asn-bank', name: 'ASN Bank' },
      },
      {
        name: 'nl-triodos-bank',
        displayName: 'Triodos Bank NL',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Dutch Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'NL',
        financialInstitution: { id: 'nl-triodos-bank', name: 'Triodos Bank NL' },
      },
      {
        name: 'nl-bunq',
        displayName: 'bunq NL',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'Dutch Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'NL',
        financialInstitution: { id: 'nl-bunq', name: 'bunq NL' },
      },
      {
        name: 'nl-knab',
        displayName: 'Knab',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Dutch Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'NL',
        financialInstitution: { id: 'nl-knab', name: 'Knab' },
      },
      // Belgian Banks
      {
        name: 'be-kbc',
        displayName: 'KBC',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'Belgian Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'BE',
        financialInstitution: { id: 'be-kbc', name: 'KBC' },
      },
      {
        name: 'be-bnp-paribas-fortis',
        displayName: 'BNP Paribas Fortis',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'Belgian Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'BE',
        financialInstitution: { id: 'be-bnp-paribas-fortis', name: 'BNP Paribas Fortis' },
      },
      {
        name: 'be-belfius',
        displayName: 'Belfius',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'Belgian Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'BE',
        financialInstitution: { id: 'be-belfius', name: 'Belfius' },
      },
      {
        name: 'be-ing',
        displayName: 'ING Belgium',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Belgian Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'BE',
        financialInstitution: { id: 'be-ing', name: 'ING Belgium' },
      },
      {
        name: 'be-argenta',
        displayName: 'Argenta',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Belgian Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'BE',
        financialInstitution: { id: 'be-argenta', name: 'Argenta' },
      },
      {
        name: 'be-axa-bank',
        displayName: 'AXA Bank Belgium',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Belgian Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'BE',
        financialInstitution: { id: 'be-axa-bank', name: 'AXA Bank Belgium' },
      },
      // Swedish Banks
      {
        name: 'se-swedbank',
        displayName: 'Swedbank',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'Swedish Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'SE',
        financialInstitution: { id: 'se-swedbank', name: 'Swedbank' },
      },
      {
        name: 'se-seb',
        displayName: 'SEB',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'Swedish Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'SE',
        financialInstitution: { id: 'se-seb', name: 'SEB' },
      },
      {
        name: 'se-handelsbanken',
        displayName: 'Handelsbanken',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'Swedish Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'SE',
        financialInstitution: { id: 'se-handelsbanken', name: 'Handelsbanken' },
      },
      {
        name: 'se-nordea',
        displayName: 'Nordea Sweden',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Swedish Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'SE',
        financialInstitution: { id: 'se-nordea', name: 'Nordea Sweden' },
      },
      {
        name: 'se-lansforsakringar',
        displayName: 'Länsförsäkringar',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Swedish Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'SE',
        financialInstitution: { id: 'se-lansforsakringar', name: 'Länsförsäkringar' },
      },
      {
        name: 'se-avanza',
        displayName: 'Avanza',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'Swedish Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'SE',
        financialInstitution: { id: 'se-avanza', name: 'Avanza' },
      },
      // Danish Banks
      {
        name: 'dk-danske-bank',
        displayName: 'Danske Bank',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'Danish Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'DK',
        financialInstitution: { id: 'dk-danske-bank', name: 'Danske Bank' },
      },
      {
        name: 'dk-nordea',
        displayName: 'Nordea Denmark',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'Danish Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'DK',
        financialInstitution: { id: 'dk-nordea', name: 'Nordea Denmark' },
      },
      {
        name: 'dk-jyske-bank',
        displayName: 'Jyske Bank',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Danish Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'DK',
        financialInstitution: { id: 'dk-jyske-bank', name: 'Jyske Bank' },
      },
      {
        name: 'dk-nykredit',
        displayName: 'Nykredit',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Danish Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'DK',
        financialInstitution: { id: 'dk-nykredit', name: 'Nykredit' },
      },
      {
        name: 'dk-sydbank',
        displayName: 'Sydbank',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Danish Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'DK',
        financialInstitution: { id: 'dk-sydbank', name: 'Sydbank' },
      },
      {
        name: 'dk-spar-nord',
        displayName: 'Spar Nord',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Danish Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'DK',
        financialInstitution: { id: 'dk-spar-nord', name: 'Spar Nord' },
      },
      // Norwegian Banks
      {
        name: 'no-dnb',
        displayName: 'DNB',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'Norwegian Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'NO',
        financialInstitution: { id: 'no-dnb', name: 'DNB' },
      },
      {
        name: 'no-nordea',
        displayName: 'Nordea Norway',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'Norwegian Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'NO',
        financialInstitution: { id: 'no-nordea', name: 'Nordea Norway' },
      },
      {
        name: 'no-sparebank1',
        displayName: 'SpareBank 1',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Norwegian Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'NO',
        financialInstitution: { id: 'no-sparebank1', name: 'SpareBank 1' },
      },
      {
        name: 'no-handelsbanken',
        displayName: 'Handelsbanken Norway',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Norwegian Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'NO',
        financialInstitution: { id: 'no-handelsbanken', name: 'Handelsbanken Norway' },
      },
      {
        name: 'no-sbanken',
        displayName: 'Sbanken',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'Norwegian Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'NO',
        financialInstitution: { id: 'no-sbanken', name: 'Sbanken' },
      },
      // Finnish Banks
      {
        name: 'fi-nordea',
        displayName: 'Nordea Finland',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'Finnish Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'FI',
        financialInstitution: { id: 'fi-nordea', name: 'Nordea Finland' },
      },
      {
        name: 'fi-op-financial',
        displayName: 'OP Financial Group',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'Finnish Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'FI',
        financialInstitution: { id: 'fi-op-financial', name: 'OP Financial Group' },
      },
      {
        name: 'fi-danske-bank',
        displayName: 'Danske Bank Finland',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Finnish Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'FI',
        financialInstitution: { id: 'fi-danske-bank', name: 'Danske Bank Finland' },
      },
      {
        name: 'fi-s-pankki',
        displayName: 'S-Pankki',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Finnish Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'FI',
        financialInstitution: { id: 'fi-s-pankki', name: 'S-Pankki' },
      },
      {
        name: 'fi-aktia',
        displayName: 'Aktia',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Finnish Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'FI',
        financialInstitution: { id: 'fi-aktia', name: 'Aktia' },
      },
      // Irish Banks
      {
        name: 'ie-bank-of-ireland',
        displayName: 'Bank of Ireland',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'Irish Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'IE',
        financialInstitution: { id: 'ie-bank-of-ireland', name: 'Bank of Ireland' },
      },
      {
        name: 'ie-aib',
        displayName: 'AIB',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'Irish Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'IE',
        financialInstitution: { id: 'ie-aib', name: 'AIB' },
      },
      {
        name: 'ie-permanent-tsb',
        displayName: 'Permanent TSB',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Irish Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'IE',
        financialInstitution: { id: 'ie-permanent-tsb', name: 'Permanent TSB' },
      },
      {
        name: 'ie-ulster-bank',
        displayName: 'Ulster Bank Ireland',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Irish Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'IE',
        financialInstitution: { id: 'ie-ulster-bank', name: 'Ulster Bank Ireland' },
      },
      {
        name: 'ie-kbc',
        displayName: 'KBC Ireland',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Irish Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'IE',
        financialInstitution: { id: 'ie-kbc', name: 'KBC Ireland' },
      },
      {
        name: 'ie-revolut',
        displayName: 'Revolut Ireland',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'Irish Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'IE',
        financialInstitution: { id: 'ie-revolut', name: 'Revolut Ireland' },
      },
      // Swiss Banks
      {
        name: 'ch-ubs',
        displayName: 'UBS',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'Swiss Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'CH',
        financialInstitution: { id: 'ch-ubs', name: 'UBS' },
      },
      {
        name: 'ch-credit-suisse',
        displayName: 'Credit Suisse',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'Swiss Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'CH',
        financialInstitution: { id: 'ch-credit-suisse', name: 'Credit Suisse' },
      },
      {
        name: 'ch-zkb',
        displayName: 'ZKB (Zürcher Kantonalbank)',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'Swiss Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'CH',
        financialInstitution: { id: 'ch-zkb', name: 'ZKB (Zürcher Kantonalbank)' },
      },
      {
        name: 'ch-raiffeisen',
        displayName: 'Raiffeisen Switzerland',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Swiss Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'CH',
        financialInstitution: { id: 'ch-raiffeisen', name: 'Raiffeisen Switzerland' },
      },
      {
        name: 'ch-postfinance',
        displayName: 'PostFinance',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: true,
        fields: defaultFields,
        groupDisplayName: 'Swiss Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'CH',
        financialInstitution: { id: 'ch-postfinance', name: 'PostFinance' },
      },
      {
        name: 'ch-julius-baer',
        displayName: 'Julius Bär',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Swiss Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'CH',
        financialInstitution: { id: 'ch-julius-baer', name: 'Julius Bär' },
      },
      {
        name: 'ch-migros-bank',
        displayName: 'Migros Bank',
        type: 'BANK',
        status: 'ENABLED',
        credentialsType: 'THIRD_PARTY_AUTHENTICATION',
        isPopular: false,
        fields: defaultFields,
        groupDisplayName: 'Swiss Banks',
        capabilities: defaultCapabilities,
        accessType: 'OPEN_BANKING',
        market: 'CH',
        financialInstitution: { id: 'ch-migros-bank', name: 'Migros Bank' },
      },
    ];

    // Filter by market if provided
    if (market) {
      return allProviders.filter(p => p.market === market.toUpperCase());
    }
    return allProviders;
  }

  /**
   * Generate mock authorization URL
   */
  static generateMockAuthorizationUrl(clientId: string, redirectUri: string, state: string): string {
    return `https://link.tink.com/1.0/authorize?client_id=${clientId}&redirect_uri=${encodeURIComponent(redirectUri)}&state=${state}&market=DE&locale=en_US&test=true`;
  }
}
