/**
 * Tax Deadline Controller
 * REST API endpoints for tax deadline management
 *
 * Endpoints:
 * - GET    /api/tax/deadlines          - List all deadlines
 * - POST   /api/tax/deadlines          - Create a deadline
 * - GET    /api/tax/deadlines/:id      - Get specific deadline
 * - PUT    /api/tax/deadlines/:id      - Update deadline
 * - DELETE /api/tax/deadlines/:id      - Delete deadline
 * - PUT    /api/tax/deadlines/:id/filed - Mark as filed
 * - GET    /api/tax/deadlines/upcoming - Get upcoming deadlines
 * - GET    /api/tax/deadlines/overdue  - Get overdue deadlines
 * - POST   /api/tax/deadlines/auto-generate - Auto-generate deadlines
 * - GET    /api/tax/deadlines/export/ical - Export to iCal
 */

import {
  Controller,
  Get,
  Post,
  Put,
  Delete,
  Body,
  Param,
  Query,
  UseGuards,
  Req,
  HttpCode,
  HttpStatus,
  Header,
} from '@nestjs/common';
import {
  ApiTags,
  ApiOperation,
  ApiResponse,
  ApiBearerAuth,
  ApiParam,
  ApiQuery,
} from '@nestjs/swagger';
import { JwtAuthGuard } from '@/modules/auth/guards/jwt-auth.guard';
import { RolesGuard } from '@/modules/auth/guards/roles.guard';
import { Roles } from '@/modules/auth/decorators/roles.decorator';
import { TaxDeadlineService } from './tax-deadline.service';
import {
  CreateTaxDeadlineDto,
  UpdateTaxDeadlineDto,
  MarkFiledDto,
  QueryTaxDeadlineDto,
} from './dto';

@ApiTags('Tax Deadlines')
@ApiBearerAuth()
@Controller('tax/deadlines')
@UseGuards(JwtAuthGuard, RolesGuard)
export class TaxDeadlineController {
  constructor(private readonly taxDeadlineService: TaxDeadlineService) {}

  @Post()
  @Roles('admin', 'tax_admin', 'accountant')
  @ApiOperation({ summary: 'Create a new tax deadline' })
  @ApiResponse({ status: 201, description: 'Tax deadline created successfully' })
  @ApiResponse({ status: 400, description: 'Invalid input' })
  @ApiResponse({ status: 401, description: 'Unauthorized' })
  async create(@Body() createDto: CreateTaxDeadlineDto) {
    return this.taxDeadlineService.create(createDto);
  }

  @Get()
  @Roles('admin', 'tax_admin', 'accountant', 'user')
  @ApiOperation({ summary: 'Get all tax deadlines with filtering' })
  @ApiResponse({ status: 200, description: 'List of tax deadlines' })
  async findAll(@Query() query: QueryTaxDeadlineDto) {
    return this.taxDeadlineService.findAll(query);
  }

  @Get('upcoming')
  @Roles('admin', 'tax_admin', 'accountant', 'user')
  @ApiOperation({ summary: 'Get upcoming deadlines for current organization' })
  @ApiQuery({
    name: 'days',
    required: false,
    type: Number,
    description: 'Number of days to look ahead (default: 30)',
  })
  @ApiResponse({ status: 200, description: 'List of upcoming deadlines' })
  async getUpcoming(
    @Req() req,
    @Query('days') days?: string,
  ) {
    const organizationId = req.user.organizationId;
    const daysAhead = days ? parseInt(days, 10) : 30;
    return this.taxDeadlineService.getUpcomingDeadlines(organizationId, daysAhead);
  }

  @Get('overdue')
  @Roles('admin', 'tax_admin', 'accountant', 'user')
  @ApiOperation({ summary: 'Get overdue deadlines for current organization' })
  @ApiResponse({ status: 200, description: 'List of overdue deadlines' })
  async getOverdue(@Req() req) {
    const organizationId = req.user.organizationId;
    return this.taxDeadlineService.getOverdueDeadlines(organizationId);
  }

  @Post('auto-generate')
  @Roles('admin', 'tax_admin')
  @ApiOperation({ summary: 'Auto-generate tax deadlines for a year' })
  @ApiQuery({ name: 'countryCode', required: true, type: String, example: 'DE' })
  @ApiQuery({ name: 'year', required: true, type: Number, example: 2024 })
  @ApiResponse({ status: 201, description: 'Deadlines generated successfully' })
  async autoGenerate(
    @Req() req,
    @Query('countryCode') countryCode: string,
    @Query('year') year: string,
  ) {
    const organizationId = req.user.organizationId;
    const yearNum = parseInt(year, 10);
    return this.taxDeadlineService.autoGenerateDeadlines(organizationId, countryCode, yearNum);
  }

  @Get('export/ical')
  @Roles('admin', 'tax_admin', 'accountant', 'user')
  @ApiOperation({ summary: 'Export deadlines to iCal format' })
  @ApiResponse({
    status: 200,
    description: 'iCal file content',
    content: { 'text/calendar': {} },
  })
  @Header('Content-Type', 'text/calendar; charset=utf-8')
  @Header('Content-Disposition', 'attachment; filename="tax-deadlines.ics"')
  async exportToICal(@Req() req) {
    const organizationId = req.user.organizationId;
    return this.taxDeadlineService.exportToICal(organizationId);
  }

  @Get(':id')
  @Roles('admin', 'tax_admin', 'accountant', 'user')
  @ApiOperation({ summary: 'Get a specific tax deadline by ID' })
  @ApiParam({ name: 'id', description: 'Tax deadline ID' })
  @ApiResponse({ status: 200, description: 'Tax deadline details' })
  @ApiResponse({ status: 404, description: 'Deadline not found' })
  async findOne(@Param('id') id: string) {
    return this.taxDeadlineService.findOne(id);
  }

  @Put(':id')
  @Roles('admin', 'tax_admin', 'accountant')
  @ApiOperation({ summary: 'Update a tax deadline' })
  @ApiParam({ name: 'id', description: 'Tax deadline ID' })
  @ApiResponse({ status: 200, description: 'Tax deadline updated successfully' })
  @ApiResponse({ status: 404, description: 'Deadline not found' })
  async update(
    @Param('id') id: string,
    @Body() updateDto: UpdateTaxDeadlineDto,
  ) {
    return this.taxDeadlineService.update(id, updateDto);
  }

  @Put(':id/filed')
  @Roles('admin', 'tax_admin', 'accountant')
  @ApiOperation({ summary: 'Mark a tax deadline as filed' })
  @ApiParam({ name: 'id', description: 'Tax deadline ID' })
  @ApiResponse({ status: 200, description: 'Deadline marked as filed' })
  @ApiResponse({ status: 404, description: 'Deadline not found' })
  async markAsFiled(
    @Param('id') id: string,
    @Body() markFiledDto: MarkFiledDto,
    @Req() req,
  ) {
    const userId = req.user.id;
    return this.taxDeadlineService.markAsFiled(id, markFiledDto, userId);
  }

  @Delete(':id')
  @Roles('admin', 'tax_admin')
  @HttpCode(HttpStatus.NO_CONTENT)
  @ApiOperation({ summary: 'Delete a tax deadline' })
  @ApiParam({ name: 'id', description: 'Tax deadline ID' })
  @ApiResponse({ status: 204, description: 'Deadline deleted successfully' })
  @ApiResponse({ status: 404, description: 'Deadline not found' })
  async remove(@Param('id') id: string) {
    await this.taxDeadlineService.remove(id);
  }
}
